name: Terraform Workflow

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0  # Change this to your Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Add more steps as needed, such as testing, validation, etc.
